### ISSUE TITLE
strange check in SeoAdminFactory

### ISSUE THREAD

**Issue by dbu** [symfony-cmf/sonata-admin-integration-bundle#15]
as per the discussion in https://github.com/symfony-cmf/sonata-admin-integration-bundle/pull/7/files#r90769854 do we have a hard dependency for the burgov bundle for the seo admin, or is it optional? either adjust the wording of the exception, or add checks if we need to throw the exception

**Comment by ElectricMaxxx** [comment]
not sure anymore if it was right to move the exception into the integration-bundle. We introduced that exception, cause we can't use the arbitary metadata values in admin without the help of that dependency.

**Comment by dbu** [comment]
is arbitrary metadata values a required feature? or optional in the admin? can we make a config to enable/disable that and only throw the exception if enabled but no burgov? maybe with an enabled true|false|auto?

**Comment by ElectricMaxxx** [comment]
The values arn't required on seo metadata. But the form `SeoMetadataType` isn't calm atm. So we just need to pass your information into the form as a service definition. Btw: that class need some form type refactoring.

**Comment by ElectricMaxxx** [comment]
We do need that bundle in seo-bundle as well, cause the form type of that component is needed in `Symfony\Cmf\Bundle\SeoBundle\Form\Type\SeoMetadataType`. So the seo-bundle would fail, when using  SeoAdminExtension here.

**Comment by ElectricMaxxx** [comment]
This should be done by #43
