### ISSUE TITLE
Align form_group parameters

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony-cmf/sonata-admin-integration-bundle#27]
started with seo, routing and core-bundle we have a form_group parameter per bundle, I think we forgot it in block-bundle (and others?) There we have to create more then one.

**Comment by ElectricMaxxx** [comment]
Note: The block-bundle has no form group parameters at all.

**Comment by wouterj** [comment]
Directly related to https://github.com/symfony-cmf/sonata-admin-integration-bundle/issues/4

**Comment by ElectricMaxxx** [comment]
@wouterj should have been fixed right?
