### ISSUE TITLE
Remove deprecations

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony-cmf/sonata-admin-integration-bundle#29]
Currently (when merging core-bundle integration) we have 1272 deprecation warnings. This should be decreased.

**Comment by wouterj** [comment]
We can remove some of the SonataAdminBundle deprecations, but we can't fix them all (as we have to support lower versions). Also notice that most of the deprecations are coming from Sonata's code (mostly Twig deprecations).

**Comment by ElectricMaxxx** [comment]
Sure we can't remove them all. But should have a look for those we are responsible for.
