### ISSUE TITLE
should class parameters be configurable?

### ISSUE THREAD

**Issue by dbu** [symfony-cmf/sonata-admin-integration-bundle#34]
see https://github.com/symfony-cmf/sonata-admin-integration-bundle/pull/31#discussion_r91841314

**Comment by dbu** [comment]
i would vote to remove the config for admin classes, i don't see any special value. people can use a compiler pass like for everything else.

i think its more of a question if the model classes should be configurable. that could make more sense. altough when you have a custom model, you likely also need to extend the admin for the additional features of your model, so i propose to remove that as well.

**Comment by ElectricMaxxx** [comment]
I would vote to remove them too. 
When I am right, we had one in content-bundle and many in block-bundle. For the last I would like to ask @‪lsmith‬ if he had a special purpose, when creating them.

**Comment by dbu** [comment]
max, that would be @lsmith77 - without the number, its a different person that is not involved with the cmf.

**Comment by lsmith77** [comment]
don't remember the original reason .. it might just predate compiler passes :)

**Comment by ElectricMaxxx** [comment]
Ok. Then we have two votes to remove both. Document and AdminClass configuration.

**Comment by dbu** [comment]
@wouterj would you object to removing those class parameters? both document and admin classes?

**Comment by wouterj** [comment]
I don't have a real opinion on this issue. So let's drop it.
