### ISSUE TITLE
Move translation catalogues to this bundle

### ISSUE THREAD

**Issue by wouterj** [symfony-cmf/sonata-admin-integration-bundle#42]
Currently, all translation catalogues still live in the core bundles. They should be moved to this bundle.

We may have to split it in some catalogues, to avoid conflicts.

**Comment by ElectricMaxxx** [comment]
:+1: 

Each its own catalogue to separate them or all in one `CmfSonataAdminBundle` catalogue?

**Comment by wouterj** [comment]
I think there is quite some overlap that we can fix, so I prefer to keep as much as possible in one catalogue
