### ISSUE TITLE
Wrong admin service id for route admin

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony-cmf/sonata-admin-integration-bundle#44]
IS:
cmf_sonata_admin_integration.route_admin

SHOULD:
cmf_sonata_admin_integration.routing.route_admin

**Comment by wouterj** [comment]
I propose to also rename the SEO extension service id:

*Before*
`cmf_sonata_admin_integration.seo.admin_extension`

*After*
`cmf_sonata_admin_integration.seo.extension.metadata`

This is consistent with other extension service IDs.

**Comment by ElectricMaxxx** [comment]
argh, i acidently pushed that fix to master ... :-)
my console was on:
```
maximilian@maximilian-ThinkPad-T540p:~/OpenSource/Cmf/sonata-admin$ git checkout correct_admin_service_id
```
but i forgot the enter ...
and pushed with the IDE.
Sorry for that.

**Comment by ElectricMaxxx** [comment]
But build was green, even when our main icon shows red/error.

**Comment by wouterj** [comment]
We used an incorrect status icon url. Fixed it in https://github.com/symfony-cmf/sonata-admin-integration-bundle/commit/5b83d671dc31490051b318c2c4fa712662b87349
