### ISSUE TITLE
Add missing translation ids

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony-cmf/sonata-admin-integration-bundle#50]
(for all defined languages)

Dashboard:
![auswahl_066](https://cloud.githubusercontent.com/assets/2905834/21329097/3472209e-c637-11e6-823d-836c17790e51.png)

List Content:
![auswahl_067](https://cloud.githubusercontent.com/assets/2905834/21329111/4acc731c-c637-11e6-8982-d0caca28d147.png)

List SimpleBlock
![auswahl_068](https://cloud.githubusercontent.com/assets/2905834/21329131/6ef824d4-c637-11e6-9b64-14f1d5f93bb7.png)

menu node create:
![auswahl_069](https://cloud.githubusercontent.com/assets/2905834/21329209/cea8e526-c637-11e6-9ad2-42d2fe388c77.png)

route create:
![auswahl_070](https://cloud.githubusercontent.com/assets/2905834/21329519/6e841ce0-c639-11e6-9fae-e91eaa26e4da.png)

content create:
![auswahl_071](https://cloud.githubusercontent.com/assets/2905834/21329549/8e07305c-c639-11e6-8496-35fc72af963c.png)

**Comment by wouterj** [comment]
Only some `CmfSonataAdminIntegrationBundle` are relevant here. This means these have to be added:

 * Content
   * `form.label_key`
   * `form.label_value` 
 * Routing
   * Change route options/defaults to set `label_format` to `form.label_%name%`
   * `form.label_compiler_class`
   * `form.label_controller`
   * `form.label_template`
   * `form.label_type`

All others are either CMF sandbox specific (the `demo_seo_content` ones) or automatic translations that don't have to be translate (most other ones.)
