### ISSUE TITLE
Admin classes into an PHPCR context

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony-cmf/sonata-admin-integration-bundle#61]
As currently all admins are completely related to PHPCR I would put them into a PHPCR context then. That would mean, we have to put them into PHPCR director and namespace. The service definition files still have that seperation. 

Doing so we can simply add an ORM support later by adding own ORM admins without moving the phpcr admins (BC-Break).

**Comment by dbu** [comment]
how much of this bundle is useful for orm admins? could we just rename the bundle to limit it to phpcr? we have the explicit dependency on sonata phpcr-admin and if we want to be orm and phpcr, we should not have that...

**Comment by ElectricMaxxx** [comment]
I would make the dependency not explicit, means suggests it only. Even, when the complete bundle has no sense then. But we would keep the door open to add the orm admins then (for the orm parts we have).

**Comment by dbu** [comment]
all code in this bundle is admin classes that extend Sonata\DoctrinePHPCRAdminBundle\Admin\Admin . i think we should make this explicitly the phpcr admin bundle and provide a separate orm admin bundle if somebody does that. the idea is to move more of the logic back to the bundles as symfony form types. i fear that having both orm and phpcr in the same bundle makes things tricky, and dependencies are not clearly modelled and we gain nothing from it.

**Comment by wouterj** [comment]
👍 For making this bundle pure PHPCR, I like that idea. Only the Seo extension can be used for both, but it's simple to implement anyways.

This also means we have clear dependencies, clear packages, etc.
